# Generated by Django 3.2.8 on 2022-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employer_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
