# Generated by Django 3.2.8 on 2022-09-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_employer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225, unique=True)),
                ('company_code', models.CharField(max_length=225, unique=True)),
            ],
        ),
    ]
