# Generated by Django 3.2.8 on 2022-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
