# Generated by Django 4.2.1 on 2023-05-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230426_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('employer_code', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('morning_shift', models.CharField(max_length=255)),
                ('evening_shift', models.CharField(max_length=255)),
            ],
        ),
    ]
