# Generated by Django 4.2.1 on 2024-01-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='evening_shift',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='morning_shift',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
